# Generated by Django 3.2.3 on 2021-05-23 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_remove_movie_heros'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='heros',
            field=models.ManyToManyField(related_name='heros', to='movies.Hero'),
        ),
    ]
