# Generated by Django 3.2.3 on 2021-05-23 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_movie_heros'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='heros',
        ),
        migrations.AddField(
            model_name='movie',
            name='heros',
            field=models.TextField(default=''),
        ),
        migrations.DeleteModel(
            name='Hero',
        ),
    ]
