# Generated by Django 3.2.3 on 2021-05-24 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_auto_20210525_0408'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='content',
            field=models.TextField(default='review_overview'),
        ),
        migrations.AlterField(
            model_name='review',
            name='title',
            field=models.CharField(default='review', max_length=50),
        ),
    ]
